# Generated by Django 4.1.7 on 2023-04-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_requesttypes_viedoproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viedoproject',
            name='type_request',
            field=models.CharField(choices=[('Content Repurposing', 'Content Repurposing'), ('1', ''), ('1', ''), ('1', '')], max_length=200),
        ),
    ]
