# Generated by Django 4.1.7 on 2023-04-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_viedoproject_type_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment_viedoAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachment_viedo', models.FileField(upload_to='files/upload')),
            ],
        ),
        migrations.CreateModel(
            name='Loom_linkAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loom_Videolink', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='RequestTypes',
        ),
        migrations.RenameField(
            model_name='viedoproject',
            old_name='pro_title',
            new_name='project_title',
        ),
        migrations.AlterField(
            model_name='viedoproject',
            name='type_request',
            field=models.CharField(choices=[('Content Repurposing', 'Content Repurposing'), ('Simple Video Edit', 'Simple Video Edit'), ('Motion Graphics', 'Motion Graphics'), ('Social Media Video Ad', 'Social Media Video Ad')], max_length=200),
        ),
        migrations.AlterField(
            model_name='viedoproject',
            name='Attachment_viedo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Viedo_Project', to='project.attachment_viedoadd'),
        ),
        migrations.AlterField(
            model_name='viedoproject',
            name='Loom_Videolink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Viedo_Project', to='project.loom_linkadd'),
        ),
    ]
