# Generated by Django 4.1.7 on 2023-04-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_attachment_viedoadd_loom_linkadd_delete_requesttypes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loom_linkadd',
            old_name='Loom_Videolink',
            new_name='Loom_videolink',
        ),
        migrations.RenameField(
            model_name='viedoproject',
            old_name='Attachment_viedo',
            new_name='Attachment_viedoAdd',
        ),
        migrations.RenameField(
            model_name='viedoproject',
            old_name='Loom_Videolink',
            new_name='Loom_linkAdd',
        ),
    ]
